# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robocin/pb/ssl/vision/ball.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from robocin.pb.ssl.vision import robot_pb2 as robocin_dot_pb_dot_ssl_dot_vision_dot_robot__pb2
from robocin.pb.utility import geometry_pb2 as robocin_dot_pb_dot_utility_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n robocin/pb/ssl/vision/ball.proto\x12\x15robocin.pb.ssl.vision\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!robocin/pb/ssl/vision/robot.proto\x1a!robocin/pb/utility/geometry.proto\"\xb6\x04\n\x04\x42\x61ll\x12.\n\x08position\x18\x01 \x01(\x0b\x32\x1c.robocin.pb.utility.Point3Df\x12.\n\x08velocity\x18\x02 \x01(\x0b\x32\x1c.robocin.pb.utility.Point3Df\x12J\n\x10kick_information\x18\x04 \x01(\x0b\x32+.robocin.pb.ssl.vision.Ball.KickInformationH\x00\x88\x01\x01\x1a\xe6\x02\n\x0fKickInformation\x12\x37\n\x0brobot_color\x18\x01 \x01(\x0e\x32\".robocin.pb.ssl.vision.Robot.Color\x12\x10\n\x08robot_id\x18\x02 \x01(\x05\x12\x34\n\x0estart_position\x18\x03 \x01(\x0b\x32\x1c.robocin.pb.utility.Point2Df\x12\x34\n\x0estart_velocity\x18\x04 \x01(\x0b\x32\x1c.robocin.pb.utility.Point3Df\x12\x33\n\x0fstart_timestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\rstop_position\x18\x06 \x01(\x0b\x32\x1c.robocin.pb.utility.Point2Df\x12\x32\n\x0estop_timestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x13\n\x11_kick_informationJ\x04\x08\x03\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robocin.pb.ssl.vision.ball_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BALL']._serialized_start=163
  _globals['_BALL']._serialized_end=729
  _globals['_BALL_KICKINFORMATION']._serialized_start=344
  _globals['_BALL_KICKINFORMATION']._serialized_end=702
# @@protoc_insertion_point(module_scope)
