# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robocin/pb/ssl/vision/field.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!robocin/pb/ssl/vision/field.proto\x12\x15robocin.pb.ssl.vision\"\xd6\x01\n\x05\x46ield\x12\x11\n\tserial_id\x18\x01 \x01(\x04\x12\x0e\n\x06length\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x12\n\ngoal_depth\x18\x04 \x01(\x02\x12\x12\n\ngoal_width\x18\x05 \x01(\x02\x12\x1a\n\x12penalty_area_depth\x18\x06 \x01(\x02\x12\x1a\n\x12penalty_area_width\x18\x07 \x01(\x02\x12\x16\n\x0e\x62oundary_width\x18\x08 \x01(\x02\x12#\n\x1bgoal_center_to_penalty_mark\x18\t \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robocin.pb.ssl.vision.field_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FIELD']._serialized_start=61
  _globals['_FIELD']._serialized_end=275
# @@protoc_insertion_point(module_scope)
