# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robocin/pb/ssl/vision/frame.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from robocin.pb.ssl.vision import ball_pb2 as robocin_dot_pb_dot_ssl_dot_vision_dot_ball__pb2
from robocin.pb.ssl.vision import field_pb2 as robocin_dot_pb_dot_ssl_dot_vision_dot_field__pb2
from robocin.pb.ssl.vision import robot_pb2 as robocin_dot_pb_dot_ssl_dot_vision_dot_robot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!robocin/pb/ssl/vision/frame.proto\x12\x15robocin.pb.ssl.vision\x1a\x1fgoogle/protobuf/timestamp.proto\x1a robocin/pb/ssl/vision/ball.proto\x1a!robocin/pb/ssl/vision/field.proto\x1a!robocin/pb/ssl/vision/robot.proto\"\xde\x01\n\x05\x46rame\x12\x11\n\tserial_id\x18\x01 \x01(\x04\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\x04\x62\x61ll\x18\x03 \x01(\x0b\x32\x1b.robocin.pb.ssl.vision.Ball\x12,\n\x06robots\x18\x04 \x03(\x0b\x32\x1c.robocin.pb.ssl.vision.Robot\x12\x30\n\x05\x66ield\x18\x05 \x01(\x0b\x32\x1c.robocin.pb.ssl.vision.FieldH\x00\x88\x01\x01\x42\x08\n\x06_fieldb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robocin.pb.ssl.vision.frame_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FRAME']._serialized_start=198
  _globals['_FRAME']._serialized_end=420
# @@protoc_insertion_point(module_scope)
