# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robocin/pb/ssl/vision/robot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robocin.pb.utility import geometry_pb2 as robocin_dot_pb_dot_utility_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!robocin/pb/ssl/vision/robot.proto\x12\x15robocin.pb.ssl.vision\x1a!robocin/pb/utility/geometry.proto\"\x97\x02\n\x05Robot\x12\x31\n\x05\x63olor\x18\x01 \x01(\x0e\x32\".robocin.pb.ssl.vision.Robot.Color\x12\n\n\x02id\x18\x02 \x01(\x05\x12.\n\x08position\x18\x03 \x01(\x0b\x32\x1c.robocin.pb.utility.Point2Df\x12\r\n\x05\x61ngle\x18\x04 \x01(\x02\x12.\n\x08velocity\x18\x05 \x01(\x0b\x32\x1c.robocin.pb.utility.Point2Df\x12\x18\n\x10\x61ngular_velocity\x18\x06 \x01(\x02\"@\n\x05\x43olor\x12\x15\n\x11\x43OLOR_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x43OLOR_YELLOW\x10\x01\x12\x0e\n\nCOLOR_BLUE\x10\x02J\x04\x08\x07\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robocin.pb.ssl.vision.robot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ROBOT']._serialized_start=96
  _globals['_ROBOT']._serialized_end=375
  _globals['_ROBOT_COLOR']._serialized_start=305
  _globals['_ROBOT_COLOR']._serialized_end=369
# @@protoc_insertion_point(module_scope)
